# Generated by Django 3.2.8 on 2021-10-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_email',
            field=models.EmailField(default='abc@example.com', max_length=254),
        ),
    ]
